name: go lint
run-name: ${{ github.ref_name }} by @${{ github.actor }}
on:
  pull_request:
    paths:
      - .github/workflows/go.lint.yaml
      - .golangci.yaml
      - "**/*.go"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Build go
        run: go build ./...
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.0.2
        with:
          aqua_version: v2.2.0
      - name: Setup go tool
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      - name: Lint go
        run: golangci-lint run --fix
