name: yaml lint
run-name: ${{ github.ref_name }} by @${{ github.actor }}
on:
  pull_request:
    paths:
      - .github/workflows/yaml.lint.yaml
      - "**/*.yaml"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v4.0.2
        with:
          aqua_version: v2.2.2
      - name: Setup tool
        run: ${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin/aqua i
      - name: Yaml format lint
        run: yamlfmt -lint
